### ISSUE TITLE
Audit use of `_promote_op`

### ISSUE THREAD

**Issue by shashi** [JuliaComputing/JuliaDB.jl#131]
This has served us well so far, but increasingly there is frustration when you end up with a table of a single Any column. We need to use the `Base.map` trick as much as possible.

**Comment by piever** [comment]
Two relevant links:

- [#101](https://github.com/JuliaComputing/IndexedTables.jl/issues/101) from IndexedTables and related discussion (using list comprehension is I think a common way to get the undesired column `Any`)
- For the future [this discourse thread](https://discourse.julialang.org/t/missing-data-and-namedtuple-compatibility/8136/9), where it seems that some care is required when using `map` with `Missings` (which we don't use in this package but we will IIUC). In particular `nalimilan` links to many improvements he's been doing to base Julia about this issues.

**Comment by shashi** [comment]
Related to your second point is a behavior in `join` where we speculatively create DataValue columns when doing an outerjoin lest the right table doesn't have some matches.

**Comment by shashi** [comment]
Related to your second point is a behavior in `join` where we speculatively create DataValue columns when doing an outerjoin lest the right table doesn't have some matches.

**Comment by piever** [comment]
There's one more remark. Issue [#110](https://github.com/JuliaComputing/IndexedTables.jl/issues/110) is also probably caused by this. In general I think a drawback of the current design is that it's difficult to use `groupby` in cases where the output of `f` has many fields (which could be generated programmatically). One side of the issue is that it's difficult to generate a NamedTuple programmatically (this problem will go away in Julia 0.7). The other side is that the type of these NamedTuples won't change from one row to the next but I don't think it will be inferrable.

**Comment by piever** [comment]
This is basically fixed in IndexedTables (after https://github.com/JuliaComputing/IndexedTables.jl/pull/226 is merged). There are still a couple of uses in JuliaDB though:

- https://github.com/JuliaComputing/JuliaDB.jl/blob/master/src/join.jl#L174
- https://github.com/JuliaComputing/JuliaDB.jl/blob/master/src/join.jl#L335

But I don't know the distributed code well enough to know if it's feasible to remove those.

**Comment by piever** [comment]
Closing as now `_promote_op` is not used in either JuliaDB or IndexedTables

**Comment by joshday** [comment]
Very nice work @piever!

**Comment by shashi** [comment]
Yeah, amazing amounts of deft work! :clap:
