### ISSUE TITLE
Provide a mutation interface

### ISSUE THREAD

**Issue by mohamed82008** [JuliaComputing/JuliaDB.jl#204]
I would like to request a feature to enable mutating tables without going through the following sneaky function:

```julia
function editvalue!(t, f, i, v)
    t.columns.columns[f][i] = v
    return
end
```

**Comment by shashi** [comment]
`column(t, f)[i]=v` is the easier way to do that.

**Comment by mohamed82008** [comment]
Awesome, thanks!

**Comment by Mirage10** [comment]
the following notation looks more precise and intuitive:  t[i,f] = v . This would be brilliant.

**Comment by andreasnoack** [comment]
: the following notation looks more precise and intuitive: t[i,f] = v . This would be brilliant.

I think we should avoid array syntax for tables to discourage that people use tables similarly to matrices in the same way they do in R.

**Comment by piever** [comment]
I don't think the array syntax is appropriate here but I was wondering if one could consider using dot overloading for column access in Julia 0.7, meaning `t.x` would correspond to `column(t, :x)`:  the `column` syntax is nice and explicit but sometimes it'd be useful to have a  shorter version.

**Comment by shashi** [comment]
> `t.x`

That would be a good use of that syntax! May be more copiler-friendly code than `t[f, i]`.

An alternative is to add a `matrix` function that returns an `AbstractMatrix` view of the table... `matrix` may also be useful for passing data to ML packages. But this could become type-unstable since if the eltype is heterogenous.
